@base-url = http://localhost:3000/api/v1/shop

### Sign up
POST {{base-url}}/auth/sign-up
Content-Type: application/json

{
    "name": "congquynguyen",
    "email": "test1@gmail.com",
    "password": "congquynguyen"
}

### Sign in
POST {{base-url}}/auth/sign-in
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "congquynguyen"
}
