@base-url = http://localhost:3000/api/v1/shop

### Sign up
POST {{base-url}}/auth/sign-upp
Content-Type: application/json

{
    "name": "congquynguyen",
    "email": "congquynguyen1234@gmail.com",
    "password": "congquynguyen"
}

### Get users
GET http://localhost:3000/users
Content-Type: application/json


XStream xstream = new XStream();
xstream.allowTypesByWildcard(new String[] {"org.owasp.webgoat.**"});